ModbusClient
const ModbusFramer ModbusClient::framer
Referenced by formRequest.
bool ModbusClient::connection_status
std::string ModbusClient::ip
Referenced by ModbusTCPClient::ModbusTCPClient, ModbusTCPClient::connect.
uint16_t ModbusClient::port
Referenced by ModbusTCPClient::connect.
ModbusClient::ModbusClient(std::string ip, uint16_t port, ModbusFramer framer=ModbusFramer::RTU)
virtual bool ModbusClient::connect()=0
virtual bool ModbusClient::connect(std::string ip, uint16_t port)=0
virtual bool ModbusClient::disconnect()=0
std::shared_ptr< ModbusRequest > ModbusClient::readDiscreteInput(uint16_t register_num, uint8_t slave_id, uint8_t &value, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::readDiscreteInputs(uint16_t register_num, uint16_t count, uint8_t slave_id, std::vector< uint8_t > &values, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::readCoil(uint16_t register_num, uint8_t slave_id, uint8_t &value, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::readCoils(uint16_t register_num, uint16_t count, uint8_t slave_id, std::vector< uint8_t > &values, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::writeCoil(uint16_t register_num, uint16_t value, uint8_t slave_id, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::writeCoils(uint16_t register_num, uint16_t *values, uint16_t count, uint8_t slave_id, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::writeCoils(uint16_t register_num, const std::vector< uint16_t > &values, uint8_t slave_id, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::readInputRegister(uint16_t register_num, uint8_t slave_id, uint8_t &value, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::readInputRegisters(uint16_t register_num, uint16_t count, uint8_t slave_id, std::vector< uint8_t > &values, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::readHoldingRegister(uint16_t register_num, uint8_t slave_id, uint8_t &value, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::readHoldingRegisters(uint16_t register_num, uint16_t count, uint8_t slave_id, std::vector< uint8_t > &values, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::writeHoldingRegister(uint16_t register_num, uint16_t value, uint8_t slave_id, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::writeHoldingRegisters(uint16_t register_num, uint16_t *values, uint16_t count, uint8_t slave_id, std::vector< uint8_t > &result)
std::shared_ptr< ModbusRequest > ModbusClient::writeHoldingRegisters(uint16_t register_num, const std::vector< uint16_t > &values, uint8_t slave_id, std::vector< uint8_t > &result)
virtual void ModbusClient::readDiscreteInput(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::readDiscreteInputs(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::readCoil(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::readCoils(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::writeCoil(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::writeCoils(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::readInputRegister(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::readInputRegisters(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::readHoldingRegister(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::readHoldingRegisters(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::writeHoldingRegister(std::shared_ptr< ModbusRequest > &request)
virtual void ModbusClient::writeHoldingRegisters(std::shared_ptr< ModbusRequest > &request)
std::shared_ptr< ModbusRequest > ModbusClient::sendRawRequest(uint8_t *request, size_t request_size, uint8_t slave_id, uint8_t *response, size_t &response_size)
std::shared_ptr< ModbusRequest > ModbusClient::sendRequest(ModbusFunction function, uint8_t *buffer, size_t buffer_size, uint8_t slave_id)
uint8_t * ModbusClient::formPDU(ModbusFunction function, const uint8_t *buffer, size_t buffer_size)
uint8_t * ModbusClient::formTCPRequest(ModbusFunction function, const uint8_t *buffer, size_t buffer_size, uint8_t slave_id)
Referenced by formRequest.
uint8_t * ModbusClient::formRTURequest(ModbusFunction function, const uint8_t *buffer, size_t buffer_size, uint8_t slave_id)
Referenced by formRequest.
uint8_t * ModbusClient::formASCIIRequest(ModbusFunction function, const uint8_t *buffer, size_t buffer_size, uint8_t slave_id)
Referenced by formRequest.
uint8_t * ModbusClient::formRequest(ModbusFunction function, const uint8_t *buffer, size_t buffer_size, uint8_t slave_id)
References modbus::enums::ASCII, formASCIIRequest, formRTURequest, formTCPRequest, framer, modbus::enums::RTU, modbus::enums::TCP.