modbus::utils
void modbus::utils::parseRequest(const std::shared_ptr< ModbusRequest > &modbus_request, uint8_t *raw_request, size_t raw_request_size)
void modbus::utils::parseResponse(std::shared_ptr< ModbusRequest > &modbus_request, uint8_t *raw_response, size_t raw_response_size)
ModbusError modbus::utils::parseError(uint8_t *raw_response, size_t raw_response_req)
References modbus::enums::NO_ERROR.
void modbus::utils::crcRTU(const uint8_t *data, uint8_t size, uint8_t &msb, uint8_t &lsb)
Функция для расчета контрольной суммы для Modbus RTU пакета. data - пакет (без контрольной суммы в конце size - размер пакета (без учета контрольной суммы в конце) msb - старший байт контрольной суммы lsb - младший байт контрольной суммы
References toMsbLsb.
void modbus::utils::toMsbLsb(uint16_t data, uint8_t &lsb, uint8_t &msb)
Метод для разбиения 16-битного значения на старший и младший байты data - исходное значения lsb - младший байт исходного значения msb - старший байт исходного значения
Referenced by crcRTU, main.
void modbus::utils::toMsbLsb(uint32_t data, uint16_t &lsb, uint16_t &msb)
Метод для разбиения 32-битного значения на старшие и младшие 16-бит data - исходное значения lsb - младшие 16-бит исходного значения msb - старшие 16-бит исходного значения
void modbus::utils::fromMsbLsb(uint8_t lsb, uint8_t msb, uint16_t &data)
Метод для сбора старшего и младшего байта в одно 16-битное число lsb - младший байт исходного числа msb - старший байт исходного числа data - итоговое число в одной переменной
Referenced by main.
void modbus::utils::fromMsbLsb(uint16_t lsb, uint16_t msb, uint32_t &data)
Метод для сбора старших и младших 16 бит в одно 32-битное число lsb - младшие 16-бит исходного числа msb - старшие 16-бит исходного числа data - итоговое число в одной переменной